services:
  db:
    image: mariadb:10.11.9
    container_name: mariadb
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=seichi_portal
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    networks:
      - seichi_portal
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
  redis:
    image: redislabs/rejson:2.8.3
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - seichi_portal
    restart: always
networks:
  seichi_portal:
    name: seichi-portal-backend-network
    external: false
volumes:
  mysql_data:
