services:
  db:
    image: mariadb:11.2.2
    container_name: mariadb
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=seichi_portal
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    networks:
      - seichi_portal
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
networks:
  seichi_portal:
    name: seichi-portal-backend-network
    external: false
volumes:
  mysql_data:
