services:
  db:
    image: mariadb:10.11.11
    container_name: mariadb
    # NOTE: binlog-format=ROW は meilisync で必要
    # ref: https://www.meilisearch.com/docs/guides/database/meilisync_mysql#configure-mysql
    command: --log-bin --binlog-format=ROW
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=seichi_portal
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    networks:
      - seichi_portal
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
  redis:
    image: redislabs/rejson:99.99.98
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - seichi_portal
    restart: always
  meilisearch:
    # NOTE: meilisearch の公式 Docker イメージをそのまま使用すると、全文検索時に日本語の漢字と中国語の漢字が衝突するために検索できない場合があるため、
    # 中国語のトークン化が無効化された日本語用の Docker イメージを使用する
    # ref: https://github.com/meilisearch/meilisearch/pull/3882
    image: getmeili/meilisearch:prototype-japanese-13
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development
    networks:
      - seichi_portal
    volumes:
      - meili_data:/data.ms
    restart: always
  meilisync:
    platform: linux/x86_64
    # meilisync の Docker イメージで stable を使用すると full sync ができないため、dev を使用する
    # ref: https://github.com/long2ice/meilisync/issues/94#issuecomment-2270153002
    image: long2ice/meilisync:dev
    volumes:
      - ./docker/meilisync/config.yml:/meilisync/config.yml
    networks:
      - seichi_portal
    restart: always
networks:
  seichi_portal:
    name: seichi-portal-backend-network
    external: false
volumes:
  mysql_data:
  meili_data:
