services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./server/.env
    ports:
      - "3306:3306"
    networks:
      - seichi_portal
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
networks:
  seichi_portal:
    name: seichi-portal-backend-network
    external: false
volumes:
  mysql_data:
