services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - ./server/.env
    ports:
      - "3306:3306"
    networks:
      - seichi_portal
    restart: always
  seichi_portal_backend:
    container_name: seichi-portal-backend
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    networks:
     - seichi_portal
    depends_on:
      - db
    restart: always
networks:
  seichi_portal:
    name: seichi-portal-backend-network
    external: false
volumes:
  mysql_data:
