extend = "../Makefile.common.toml"

[tasks.generate-entity-private-task]
command = "sea-orm-cli"
args = [
    "generate",
    "entity",
    "--database-url",
    "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}",
    "-o",
    "src/entities/"
]

[tasks.generate-entity]
extend = "generate-entity-private-task"
env_files = [
    "../.env"
]

[tasks.generate-entity.windows]
extend = "generate-entity-private-task"
env_files = [
    "..\\.env"
]

[tasks.generate-migration-file]
command = "sea-orm-cli"
args = [
    "migrate",
    "generate",
    "please_change_this_name",
    "-d",
    "../migration/"
]
