[package]
name = "entrypoint"
version = "0.1.0"
edition = "2021"
default-run = "entrypoint"

[dependencies]
resource = { path = "../infra/resource" }
migration = { path = "../migration" }
presentation = { path = "../presentation" }
axum = { workspace = true }
serde = { workspace = true }
envy = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
once_cell = { workspace = true }
hyper = { version = "0.14.26", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.1", features = ["cors"] }
tracing-subscriber = "0.3.17"
tokio = { version = "1.28.2", features = ["full"] }
# default featureは推移的にnative-tls featureを有効しているため、native-tls (LinuxではOpenSSL) を連れてくる。これをオプトアウトするためにrustlsを使う。
sentry = { version = "0.31.5", default-features = false, features = ["backtrace", "contexts", "debug-images", "panic", "reqwest", "profiling", "rustls"] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
