[package]
name = "entrypoint"
version = "0.1.0"
edition = "2021"
default-run = "entrypoint"

[dependencies]
resource = { path = "../infra/resource" }
migration = { path = "../migration" }
presentation = { path = "../presentation" }
common = { path = "../common" }
axum = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
hyper = { version = "0.14.27", features = ["full"] }
tower-http = { version = "0.4.1", features = ["cors"] }
tracing-subscriber = { version = "0.3.17", features = ["std", "registry", "env-filter"] }
tokio = { version = "1.28.2", features = ["full"] }
# default featureは推移的にnative-tls featureを有効しているため、native-tls (LinuxではOpenSSL) を連れてくる。これをオプトアウトするためにrustlsを使う。
sentry = { version = "0.31.5", default-features = false, features = ["backtrace", "contexts", "panic", "anyhow", "reqwest", "profiling", "tracing", "debug-images", "rustls", "tower", "tower-http"] }

[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["user-hooks"]
