[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
errors = { path = "../errors" }
async-trait = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
mockall = { workspace = true }
derive-getters = "0.3.0"
typed-builder = "0.14.0"
strum = { workspace = true }
strum_macros = "0.25.0"
deriving_via = "1.4.0"
chrono = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true, features = ["arbitrary"] }
