[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
mockall = { workspace = true }
derive-getters = "0.2.0"
typed-builder = "0.13.0"
