[workspace]
resolver = "2"
members = [
    "common",
    "domain",
    "entrypoint",
    "errors",
    "infra/entities",
    "infra/outgoing",
    "infra/resource",
    "migration",
    "presentation",
    "types",
    "usecase",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
axum = { version = "0.6.20", features = ["headers"] }
serde = { version = "1.0.189", features = ["derive"] }
anyhow = "1.0.75"
async-trait = "0.1.74"
sea-orm = { version = "0.12.4", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.39"
mockall = "0.11.4"
envy = "0.4.2"
once_cell = "1.18.0"
test-case = "3.2.1"
strum = { version = "0.25.0", features = ["strum_macros"] }
proptest = "1.3.1"
proptest-derive = "0.4.0"
serde_json = "1.0.107"
itertools = "0.11.0"
chrono = { version = "0.4.31" }
futures = "0.3.28"
uuid = { version = "1.4.1", features = ["v4"] }
deriving_via = "1.5.0"
reqwest = { version = "0.11.22", default-features = false, features = ["rustls"] }
num-traits = "0.2.17"
regex = "1.10.2"
