[workspace]
members = ["app", "migration", "domain", "infra/resource", "infra/entities", "presentation", "usecase"]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
axum = "0.6.9"
serde = { version = "1.0.152", features = ["derive"] }
anyhow = "1.0.69"
async-trait = "0.1.65"
sea-orm = { version = "0.11.0", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.37"
mockall = "0.11.3"
envy = "0.4.2"
