[workspace]
members = [
    "common",
    "domain",
    "entrypoint",
    "errors",
    "infra/entities",
    "infra/outgoing",
    "infra/resource",
    "migration",
    "presentation",
    "types",
    "usecase",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
axum = { version = "0.6.19", features = ["headers"] }
serde = { version = "1.0.173", features = ["derive"] }
anyhow = "1.0.72"
async-trait = "0.1.72"
sea-orm = { version = "0.11.3", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.37"
mockall = "0.11.4"
envy = "0.4.2"
once_cell = "1.18.0"
test-case = "3.1.0"
strum = { version = "0.25.0", features = ["strum_macros"] }
proptest = "1.2.0"
proptest-derive = "0.3.0"
serde_json = "1.0.103"
itertools = "0.11.0"
chrono = { version = "0.4.26" }
futures = "0.3.28"
uuid = "1.4.1"
deriving_via = "1.5.0"
reqwest = { version = "0.11.18", default-features = false, features = ["rustls"] }
