[workspace]
members = [
    "entrypoint",
    "common",
    "domain",
    "infra/resource",
    "infra/entities",
    "migration",
    "presentation",
    "usecase",
    "errors",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
axum = "0.6.10"
serde = { version = "1.0.155", features = ["derive"] }
anyhow = "1.0.69"
async-trait = "0.1.66"
sea-orm = { version = "0.11.1", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.37"
mockall = "0.11.3"
envy = "0.4.2"
dotenvy = "0.15.6"
once_cell = "1.17.1"
test-case = "3.0.0"
strum = { version = "0.24.1", features = ["strum_macros"] }
proptest = "1.1.0"
proptest-derive = "0.3.0"
serde_json = "1.0.94"
