[workspace]
members = [
    "entrypoint",
    "common",
    "domain",
    "infra/resource",
    "infra/entities",
    "migration",
    "presentation",
    "usecase",
    "errors",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
axum = "0.6.18"
serde = { version = "1.0.164", features = ["derive"] }
anyhow = "1.0.71"
async-trait = "0.1.68"
sea-orm = { version = "0.11.3", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.37"
mockall = "0.11.4"
envy = "0.4.2"
once_cell = "1.18.0"
test-case = "3.1.0"
strum = { version = "0.24.1", features = ["strum_macros"] }
proptest = "1.2.0"
proptest-derive = "0.3.0"
serde_json = "1.0.96"
itertools = "0.10.5"
