[workspace]
resolver = "2"
members = [
    "common",
    "domain",
    "entrypoint",
    "errors",
    "infra/outgoing",
    "infra/resource",
    "migration",
    "presentation",
    "types",
    "usecase",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
tokio = { version = "1.36.0", features = ["full"] }
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["typed-header"] }
serde = { version = "1.0.197", features = ["derive"] }
anyhow = "1.0.80"
async-trait = "0.1.77"
sea-orm = { version = "1.0.0", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.40"
mockall = "0.13.0"
envy = "0.4.2"
once_cell = "1.19.0"
test-case = "3.3.1"
strum = "0.26.1"
strum_macros = "0.26.1"
proptest = "1.4.0"
proptest-derive = "0.5.0"
serde_json = "1.0.114"
itertools = "0.13.0"
chrono = { version = "0.4.34" }
futures = "0.3.30"
uuid = { version = "1.7.0", features = ["v4", "v7"] }
deriving_via = "1.6.1"
reqwest = { version = "0.12.0", default-features = false, features = ["rustls-tls", "json"] }
num-traits = "0.2.18"
regex = "1.10.3"
redis = { version = "0.27.0", features = ["tokio-comp", "json"] }
meilisearch-sdk = "0.27.1"
