[workspace]
resolver = "2"
members = [
    "common",
    "domain",
    "entrypoint",
    "errors",
    "infra/outgoing",
    "infra/resource",
    "migration",
    "presentation",
    "types",
    "usecase",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
axum = "0.7.3"
axum-extra = { version = "0.9.1", features = ["typed-header"] }
serde = { version = "1.0.193", features = ["derive"] }
anyhow = "1.0.78"
async-trait = "0.1.76"
sea-orm = { version = "0.12.10", features = ["sqlx-mysql", "runtime-actix-rustls", "macros"] }
tracing = "0.1.40"
mockall = "0.12.1"
envy = "0.4.2"
once_cell = "1.19.0"
test-case = "3.3.1"
strum = { version = "0.25.0", features = ["strum_macros"] }
proptest = "1.4.0"
proptest-derive = "0.4.0"
serde_json = "1.0.109"
itertools = "0.12.0"
chrono = { version = "0.4.31" }
futures = "0.3.30"
uuid = { version = "1.6.1", features = ["v4"] }
deriving_via = "1.6.0"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls"] }
num-traits = "0.2.17"
regex = "1.10.2"
