[package]
name = "presentation"
version = "0.1.0"
edition = "2021"

[dependencies]
resource = { path = "../infra/resource" }
domain = { path = "../domain" }
usecase = { path = "../usecase" }
axum = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
