[package]
name = "resource"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../../domain" }
entities =  { path = "../entities" }
dotenvy = "0.15.6"
once_cell = "1.17.1"
sea-orm = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
mockall = { workspace = true }
envy = { workspace = true }
