openapi: 3.0.0
x-stoplight:
  id: gh4775ufrmb2s
info:
  title: seichi_portal_api
  version: '1.0'
  description: ''
  summary: Seichi Portal Backend API用のOpenAPIサーバー
servers:
  - url: 'http://localhost:9000'
    description: seichi_portal_backend
paths:
  /api/form/create:
    post:
      summary: ''
      operationId: post-create
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  form_name: お問い合わせフォーム
                  questions:
                    - title: 質問1
                      description: 質問1の説明
                      question_type: TEXT
                    - title: 質問2
                      description: 質問2の説明
                      question_type: PULLDOWN
                      choices:
                        - 選択肢1
                        - 選択肢2
                    - title: 質問3
                      description: 質問3の説明
                      question_type: CHECKBOX
                      choices:
                        - 選択肢1
                        - 選択肢2
              properties:
                form_name:
                  type: string
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
                      question_type:
                        type: string
                      choices:
                        type: array
                        items:
                          type: string
            examples: {}
          application/xml:
            schema:
              type: object
              properties: {}
            examples: {}
          multipart/form-data:
            schema:
              type: object
              properties:
                form_name:
                  type: string
                questions:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      description:
                        type: string
                      question_type:
                        type: string
                      choices:
                        type: array
                        items:
                          type: string
              x-examples:
                example-1:
                  form_name: お問い合わせフォーム
                  questions:
                    - title: 質問1
                      description: 質問1の説明
                      question_type: TEXT
                    - title: 質問2
                      description: 質問2の説明
                      question_type: PULLDOWN
                      choices:
                        - 選択肢1
                        - 選択肢2
                    - title: 質問3
                      description: 質問3の説明
                      question_type: CHECKBOX
                      choices:
                        - 選択肢1
                        - 選択肢2
            examples: {}
        description: ''
      x-internal: false
      description: ''
    parameters: []
components:
  schemas: {}
