name: Checking
on:
  push:

env:
  image_name: ghcr.io/giganticminecraft/seichi-poral-backend

jobs:
  lint-and-test:
    name: Lint and test server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # reads toolchain info from /rust-toolchain.toml
      # we are using a fork of actions-rs/toolchain for rust-toolchain.toml support
      # (see https://github.com/actions-rs/toolchain/pull/209) for details.
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.68.2
          target: x86_64-unknown-linux-musl
          components: clippy, rustfmt

      # > selecting a toolchain either by action or manual `rustup` calls should happen
      # > before the plugin, as it uses the current rustc version as its cache key
      # https://github.com/Swatinem/rust-cache/tree/cb2cf0cc7c5198d3364b9630e2c3d457f160790c#example-usage
      - uses: Swatinem/rust-cache@v2.2.1
        with:
          workspaces: "./server -> target"

      # buf CLIがビルドに必要
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cargo fmt
        run: cargo fmt --all -- --check
        working-directory: ./server

      - name: Cargo build
        run: cargo build
        working-directory: ./server

      - name: Clippy check
        uses: LoliGothick/clippy-check@v0.2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: --all-features --manifest-path ./server/Cargo.toml

      - name: Cargo test
        run: cargo test --all-features
        working-directory: ./server
