name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  CARGO_INCREMENTAL: 0
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2.2.0
      - name: Clippy check
        uses: LoliGothick/clippy-check@v0.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: --all-features --manifest-path ./server/Cargo.toml
      - name: Compile for unit test
        run: cargo test --no-run --locked --manifest-path ./server/Cargo.toml
      - name: Unit test
        run: cargo test --manifest-path ./server/Cargo.toml
